name: xxxxbuild_Qt6.9.2_MinGW1310_64

on: workflow_dispatch

env:
  QT_VERSION: 6.9.2
  QT_VERSION2: 6.9
  FILE_NAME: static-Release_mingw1310_64

jobs:
  windows_mingw64_static_release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install -y 7zip
        refreshenv

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Setup MinGW64
      run: |
        cd ..
        curl -L -o mingw1310.7z https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw1310/qt.tools.win64_mingw1310/13.1.0-202407240918mingw1310.7z
        7z x mingw1310.7z -oD:\a\buildQt\mingw1310_64

    - name: Setup Ninja
      run: |
        cd ..
        mkdir -p ninja
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.13.1/ninja-win.zip
        7z x ninja.zip -o./ninja

    - name: Build Qt
      run: |
        cd ..
        mkdir -p Qt
        cd Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-static
        curl -L -o qt-everywhere-src.zip https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-src-${{env.QT_VERSION}}.zip
        7z x qt-everywhere-src.zip -o./${{env.QT_VERSION}}
        cmd.exe /c "call `"D:\a\buildQt\buildQt\buildQt6\build-Qt6mingw1310_64.cmd`" > build.log 2>&1"
        type build.log
        if not exist "../Qt/${{env.QT_VERSION}}-static/mingw1310_64/bin/qmake.exe" (
          echo "Error: Qt build failed!"
          exit 1
        )

    - name: Package binaries
      run: |
        dir ../Qt/${{env.QT_VERSION}}-static/mingw1310_64
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-static/mingw1310_64 -mx=9
        7z l Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z

    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z
